// Datos iniciales para el seed de la tabla Country.
// Una vez ejecutado el seed, los países se gestionan desde el panel de admin.
export const SEED_COUNTRIES = [
  { iso: 'BO', dialCode: '+591', name: 'Bolivia',              currency: 'BOB' },
  { iso: 'AR', dialCode: '+54',  name: 'Argentina',            currency: 'ARS' },
  { iso: 'BR', dialCode: '+55',  name: 'Brasil',               currency: 'BRL' },
  { iso: 'CL', dialCode: '+56',  name: 'Chile',                currency: 'CLP' },
  { iso: 'CO', dialCode: '+57',  name: 'Colombia',             currency: 'COP' },
  { iso: 'CR', dialCode: '+506', name: 'Costa Rica',           currency: 'CRC' },
  { iso: 'DO', dialCode: '+1',   name: 'Republica Dominicana', currency: 'DOP' },
  { iso: 'EC', dialCode: '+593', name: 'Ecuador',              currency: 'USD' },
  { iso: 'SV', dialCode: '+503', name: 'El Salvador',          currency: 'USD' },
  { iso: 'GT', dialCode: '+502', name: 'Guatemala',            currency: 'GTQ' },
  { iso: 'HN', dialCode: '+504', name: 'Honduras',             currency: 'HNL' },
  { iso: 'NI', dialCode: '+505', name: 'Nicaragua',            currency: 'NIO' },
  { iso: 'PA', dialCode: '+507', name: 'Panama',               currency: 'USD' },
  { iso: 'PE', dialCode: '+51',  name: 'Peru',                 currency: 'PEN' },
  { iso: 'PY', dialCode: '+595', name: 'Paraguay',             currency: 'PYG' },
  { iso: 'UY', dialCode: '+598', name: 'Uruguay',              currency: 'UYU' },
  { iso: 'VE', dialCode: '+58',  name: 'Venezuela',            currency: 'VES' },
  { iso: 'MX', dialCode: '+52',  name: 'Mexico',               currency: 'MXN' },
  { iso: 'US', dialCode: '+1',   name: 'Estados Unidos',       currency: 'USD' },
  { iso: 'CA', dialCode: '+1',   name: 'Canada',               currency: 'CAD' },
  { iso: 'ES', dialCode: '+34',  name: 'Espana',               currency: 'EUR' },
];
